name: Deploy Live

on:
  push:
    branches: [main]

jobs:
  build:
    if: github.repository_owner	== 'PaloAltoNetworks'
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install dependencies
        run: yarn --prefer-offline

      - name: Build packages
        run: yarn build-packages

      - name: Build site
        run: yarn build-demo && zip -r build.zip demo/build

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build.zip

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - uses: actions/download-artifact@v3
        with:
          name: build

      - name: Unzip build artifact
        run: unzip build.zip

      - name: Deploy to Firebase
        id: deploy_live
        uses: FirebaseExtended/action-hosting-deploy@276388dd6c2cde23455b30293105cc866c22282d # v0.6-alpha
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PANDEV }}"
          projectId: pandev
          channelId: live
          target: docusaurus-openapi.tryingpan.dev
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
